---
title: "Goals of this tutorial"
author: "P. Adames"
date: "27/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is R

R is first a programming language designed for statistical computing and graphics. Inspired by the S language developed at Bell Labs by John Chamberland in 1976. The first stable beta version of R took 9 years to develop. I was started in 1991 by two statisticians, George Ross Ihaka and [Robert Clifford Gentleman](<https://en.wikipedia.org/wiki/Robert_Gentleman_(statistician)>), at the University of Auckland in New Zeland. Dr. Gentleman is a Canadian mathematician from the University of British Columbia and a statistician from the University of Washington, that was teaching at the University of Aukland at the time, he also started the [Bioconductor](<https://en.wikipedia.org/wiki/Bioconductor>) project and is currently the Director of the Center for Computational Biomedicine a the University of Harvard. In 1995 R became free and open-source software under the GNU General Public License. The Comprehensive R  Archive Network [(CRAN)](<https://cran.r-project.org/mirrors.html>) became official in 1997 with 3 mirrors and 12 contributed packages, today it is available in 103 mirrors, in 50 different countries, and it contains `r length(available.packages()[,'Package'])` contributed packages.

R is also a computation environment, based on S and inspired in Scheme, an implementation of lisp that includes syntactic scoping. So when people usually refer to R doing a calculation they refer to the computer's  operating system running an R interpreter executing the commands that appear  either on the command line of and R interactive console or in the lines of an R  script.

R is not a domain specific language, DSL, but a language with the power to create DSLs.

We will learn how to use both to do statistical calculations and graphics that explain the results.


## Why another tutorial on R

Because there is not a single way to teach R and abundance of resources are more likely to match learning styles.
Also each tutorial addresses different contexts and needs of the audience it is directed to, so your feedback helps adjust and modify this tutotial.

Some other tutorials are:

 - <https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf>
 - <https://datacarpentry.org/R-ecology-lesson/>

There are a myriad books that will walk you through the journey of learning the R language to instruct the computer to do amazing calculations and beautiful and informative visualizations. This is only a sampler:

 - Hands-On Programming with R. Garrett Grolemund. O'Reilly Media, Inc. 2014
 - R in Action, 2nd Ed. Robert I. Kabacoff. Manning. 2015
 - Statistical Computing in C++ and R. Ana Kupresanin and Randall L Eubank. Chapman and Hall/CRC. 2011
 - ggplot2, Elegant Graphics for Data Analysis. Hadley Wickham. Springer. 2009
 - Advanced R. Hadley Wickham. CRC Press. 2015


## Audience

The target audience is the undergraduate science and engineering student looking for a language to express statistical computations, data analysis and data visualization using modern and sound implementations vetted by a community of practicioners and peers solving common research and engineering problems.



